🔀 :: (#622)  정렬 및 필터를 기능을 연결합니다.
wakmusic/wakmusic-iOS pull request #628
Opened 2024-06-19 08:20 UTC by yongbeomkwak

## 💡 배경 및 개요

- 검색 결과 화면에 정렬 및 필터 화면 디자인 변경에 따른 재구현

Resolves: #622

## 📃 작업내용

- 필터 및 정렬 헤더 UI를 다시 구성합니다
- 실질적인 이벤트를 연결합니다.
- 필터 및 정렬 기능을 통해 데이터를 가져옵니다.

## 🙋‍♂️ 리뷰노트

> 구현 시에 고민이었던 점들 혹은 특정 부분에 대한 의도가 있었다면 PR 리뷰의 이해를 돕기 위해 서술해주세요!
>
> 또한 리뷰어에게 특정 부분에 대한 집중 혹은 코멘트 혹은 질문을 요청하는 경우에 작성하면 좋아요!
>
> e.g. 작업을 끝내야할 시간이 얼마 없어 확장성보다는 동작을 위주로 만들었어요! 감안하고 리뷰해주세요!

## ✅ PR 체크리스트

> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!

- [ ] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `XCConfig`, `노션`, `README`)
- [ ] 이 작업을 하고나서 공유해야할 팀원들에게 공유되었나요? (e.g. `"API 개발 완료됐어요"`, `"XCConfig 값 추가되었어요"`)
- [ ] 작업한 코드가 정상적으로 동작하나요?
- [ ] Merge 대상 브랜치가 올바른가요?
- [ ] PR과 관련 없는 작업이 있지는 않나요?

## 🎸 기타

2024-06-19 09:28 UTC, yongbeomkwak commented on Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/SearchFilterOptionCollectionViewLayout.swift
> +            widthDimension: .fractionalWidth(1.3),
1.0으로 했을 때 그룹 한개에 아이템이 모두 못 들어갔습니다.

2024-06-19 14:03 UTC, baekteun commented on Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/SearchFilterOptionCollectionViewLayout.swift
> +            widthDimension: .fractionalWidth(1.3),
group widthDimension에 .estimated(50)주고 item widthDimention에 fractional(1.0) 주는게 어떠신가요

2024-06-19 15:46 UTC, yongbeomkwak commented on Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/SearchFilterOptionCollectionViewLayout.swift
> +            widthDimension: .fractionalWidth(1.3),
엇 혹시 50 인 이유가 있을까요 ??

2024-06-19 15:46 UTC, baekteun commented on Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/SearchFilterOptionCollectionViewLayout.swift
> +            widthDimension: .fractionalWidth(1.3),
위에 itemSize 50주셔가지고요

2024-06-19 15:47 UTC, baekteun commented on Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/SearchFilterOptionCollectionViewLayout.swift
> +            widthDimension: .fractionalWidth(1.3),
estimated라 self sizing이 더 높게 우선순위 가져가긴해서 대충 비슷하면 크게 상관 없을거같긴해요

2024-06-19 15:47 UTC, yongbeomkwak commented on Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/SearchFilterOptionCollectionViewLayout.swift
> +            widthDimension: .fractionalWidth(1.3),
적용해보겠습니다.

2024-06-20 02:13 UTC, KangTaeHoon commented
(전체, 제목, 아티스트, 크레딧) 스크롤을 끝까지 당겼을때도 그라디언트를 벗어나지 못하네요.

2024-06-20 02:16 UTC, KangTaeHoon commented
![스크린샷 2024-06-20 오전 11 15 41](https://github.com/wakmusic/wakmusic-iOS/assets/37323252/fd53d45a-a4d7-4833-9cf2-f4c7329da240)
여기도 스크롤하면 좌측에 20만큼 차지하고있어서 제외하고 지나가는게 맞는지 전체영역으로 지나가야 하는지 체크해보셔야할듯

2024-06-20 02:29 UTC, youn9k requested changes

2024-06-20 02:29 UTC, youn9k commented on Projects/Features/SearchFeature/Sources/Reactors/ListSearchResultReactor.swift
>                      return Mutation.updateDataSource(dataSource: dataSource, canLoad: dataSource.count == limit)
```suggestion
                    return Mutation.updateDataSource(dataSource: prev+dataSource, canLoad: dataSource.count == limit)
```
이렇게 되야하는거 아닌가요?

2024-06-20 02:29 UTC, youn9k commented on Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
> +                    size: .fixed(240 + SAFEAREA_BOTTOM_HEIGHT())
<img width="715" alt="image" src="https://github.com/wakmusic/wakmusic-iOS/assets/60254939/e4aaa53a-9c38-4734-9e36-3516e6e22b5d">

```suggestion
                    size: .fixed(248 + SAFEAREA_BOTTOM_HEIGHT())
```
높이 248이 맞나요?

2024-06-20 02:29 UTC, youn9k commented on Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
> +            $0.top.equalTo(headerView.snp.bottom).offset(16)
<img width="805" alt="스크린샷 2024-06-20 오전 11 28 02" src="https://github.com/wakmusic/wakmusic-iOS/assets/60254939/47a67539-e2db-4e97-be44-5629550e50c7">

```suggestion
            $0.top.equalTo(headerView.snp.bottom).offset(8)
```
이 부분이 맞는지 모르겠는데 피그마상으론 8로 보여요

2024-06-20 02:42 UTC, KangTaeHoon commented on Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
> +                    size: .fixed(240 + SAFEAREA_BOTTOM_HEIGHT())
상, 하단 마진(20+20) + 항목갯수(하나당 52)라고하면 인기순이 없으니 (20+52+52+52+20) = 196이 맞음.
하지만, 바텀시트의 경우 콘텐츠가 적어서 너무 바닥에 붙어있으면 손가락이 움직여야 하는 범위가 넓어지므로 하단 마진을 일부러 넉넉하게 주는 경우가 있긴 했던걸로 기억함.

2024-06-20 05:28 UTC, yongbeomkwak commented on Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/SearchFilterOptionCollectionViewLayout.swift
> +
감사합니다.

2024-06-20 05:28 UTC, yongbeomkwak commented on Projects/Features/SearchFeature/Sources/Reactors/ListSearchResultReactor.swift
>                      return Mutation.updateDataSource(dataSource: dataSource, canLoad: dataSource.count == limit)
엇 맞네요

2024-06-20 05:29 UTC, yongbeomkwak commented on Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
> +            $0.top.equalTo(headerView.snp.bottom).offset(16)
저게 위 아래 간격 맞출려고 샴퓨님이랑 간격 조절한거에요

2024-06-20 05:56 UTC, youn9k commented on Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
> +            $0.top.equalTo(headerView.snp.bottom).offset(16)
아하 확인했습니당

2024-06-20 05:56 UTC, youn9k approved these changes

2024-06-20 06:09 UTC, youn9k approved these changes

2024-06-20 06:16 UTC, KangTaeHoon approved these changes

2024-06-20 13:54 UTC, merged