🔀 :: (#567) 내 정보 화면 구현
wakmusic/wakmusic-iOS pull request #675
Opened 2024-06-26 10:06 UTC by youn9k

## 💡 배경 및 개요
내 정보 화면에 변경사항들이 있어서 구현했습니다.

## 📃 작업내용

|로그인 전|로그인 후|
|---|---|
|<img width="100%" alt="스크린샷 2024-06-26 오후 7 00 55" src="https://github.com/wakmusic/wakmusic-iOS/assets/60254939/94d338fb-7db6-4d95-9fda-b53ae33c8259">| <img width="100%" alt="스크린샷 2024-06-26 오후 7 02 56" src="https://github.com/wakmusic/wakmusic-iOS/assets/60254939/5023d4b3-392c-4eda-bf17-5caa4a7150cd">|

## 🙋‍♂️ 리뷰노트
빨간 점 기능 구현이 NoticeDomain작업이 있어 분리했습니다. 해당 작업 PR에서 #567 #674 동시에 닫을게용

## ✅ PR 체크리스트

> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!

- [ ] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `XCConfig`, `노션`, `README`)
- [ ] 이 작업을 하고나서 공유해야할 팀원들에게 공유되었나요? (e.g. `"API 개발 완료됐어요"`, `"XCConfig 값 추가되었어요"`)
- [ ] 작업한 코드가 정상적으로 동작하나요?
- [ ] Merge 대상 브랜치가 올바른가요?
- [ ] PR과 관련 없는 작업이 있지는 않나요?

## 🎸 기타

2024-06-26 10:25 UTC, KangTaeHoon commented on Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift
> +
다운샘플링을 하는 이유가 뭔가요?

2024-06-26 10:27 UTC, youn9k commented on Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift
> +
원본이 400x400이더라구요 불필요하게 커서 다운샘플링했습니다

2024-06-26 10:28 UTC, KangTaeHoon commented on Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift
> +
2x, 3x 배수 이미지는 고려가 된 상태인가요?

2024-06-26 10:35 UTC, yongbeomkwak requested changes
서버에 데이터 보낼 때 ReuqestDTO 형식으로 하면 좋을 것 같아요

2024-06-26 10:35 UTC, yongbeomkwak commented on Projects/Domains/UserDomain/Sources/API/UserAPI.swift
> -            return .requestJSONEncodable(RequsetProfileModel(type: image))
Model은 제가 알기론 UI에 보여질 때 쓰는 걸로 알고 있는데

다른 쪽 보면은 RequestDTO 디렉토리 파서 거기 모아놓고 있거든요?? 그거 참고하시면 어떨까요?

2024-06-26 10:41 UTC, youn9k commented on Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift
> +
아 그렇네요 그럼 3배수 고려해서 300*300으로 하는게 맞겠네요

2024-06-26 10:54 UTC, youn9k commented on Projects/Domains/UserDomain/Sources/API/UserAPI.swift
> -            return .requestJSONEncodable(RequsetProfileModel(type: image))
좋은거같아요 레거시코드들 전부 저렇게 돼있던데 보일때마다 리팩해야겠네요

2024-06-26 11:01 UTC, KangTaeHoon approved these changes

2024-06-26 14:24 UTC, youn9k commented on Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift
> +
300*300으로 수정

2024-06-26 14:25 UTC, youn9k commented on Projects/Domains/UserDomain/Sources/API/UserAPI.swift
> -            return .requestJSONEncodable(RequsetProfileModel(type: image))
RequestDTO/SetUserNameRequestDTO, ... 리팩 완료

2024-06-27 00:18 UTC, yongbeomkwak approved these changes

2024-06-27 01:29 UTC, merged